"Resources"
{
	"materials/hud/leaderboard_class_demo_caber.vmt"	"file"
	"materials/hud/leaderboard_class_demo_caber.vtf"	"file"
	"materials/hud/leaderboard_class_demo_knight_bottle.vmt"	"file"
	"materials/hud/leaderboard_class_demo_knight_bottle_giant.vmt"	"file"
	"materials/hud/leaderboard_class_demo_knight_bottle.vtf"	"file"
	"materials/hud/leaderboard_class_demo_paintrain.vmt"	"file"
	"materials/hud/leaderboard_class_demo_paintrain.vtf"	"file"
	"materials/hud/leaderboard_class_pyro_critaxe.vmt"	"file"
	"materials/hud/leaderboard_class_pyro_critaxe.vtf"	"file"
	"materials/hud/leaderboard_class_pyro_riftaxe.vmt"	"file"
	"materials/hud/leaderboard_class_pyro_riftaxe_giant.vmt"	"file"
	"materials/hud/leaderboard_class_pyro_riftaxe.vmt"	"vtf"
	"materials/hud/leaderboard_class_scout_bat_giant.vmt"	"file"
	"materials/hud/leaderboard_class_scout_pistol_2.vmt"	"file"
	"materials/hud/leaderboard_class_scout_pistol_2.vtf"	"file"
	"materials/hud/leaderboard_class_sniper_bow_bleed.vmt"	"file"
	"materials/hud/leaderboard_class_sniper_bow_bleed.vtf"	"file"
	"materials/hud/leaderboard_class_soldier_equalizer.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_equalizer.vtf"	"file"
	
	"materials/sprites/obj_icons/icon_obj_hi_red.vmt"	"file"
	"materials/sprites/obj_icons/icon_obj_lo_red.vmt"	"file"
	"materials/sprites/obj_icons/icon_obj_hi_red_locked.vmt"	"file"
	"materials/sprites/obj_icons/icon_obj_lo_red_locked.vmt"	"file"
	"materials/sprites/obj_icons/icon_obj_hi_zom_blu.vmt"	"file"
	"materials/sprites/obj_icons/icon_obj_lo_zom_blu.vmt"	"file"
	"materials/sprites/obj_icons/icon_obj_hi_zom_blu_locked.vmt"	"file"
	"materials/sprites/obj_icons/icon_obj_lo_zom_blu_locked.vmt"	"file"
	"materials/sprites/obj_icons/icon_obj_hi_red.vtf"	"file"
	"materials/sprites/obj_icons/icon_obj_lo_red.vtf"	"file"
	"materials/sprites/obj_icons/icon_obj_hi_zom_blu.vtf"	"file"
	"materials/sprites/obj_icons/icon_obj_lo_zom_blu.vtf"	"file"
}