Resources
{
	"materials/hud/leaderboard_class_demo_loosecannon.vmt"	"file"
	"materials/hud/leaderboard_class_demo_loosecannon.vtf"	"file"
	"materials/hud/leaderboard_class_heavy_shotgun_spammer_pda.vmt"	"file"
	"materials/hud/leaderboard_class_heavy_shotgun_spammer_pda.vtf"	"file"
	"materials/hud/leaderboard_class_heavy_warrior.vmt"	"file"
	"materials/hud/leaderboard_class_heavy_warrior.vtf"	"file"
	"materials/hud/leaderboard_class_medic_battle.vmt"	"file"
	"materials/hud/leaderboard_class_medic_battle.vtf"	"file"
	"materials/hud/leaderboard_class_medic_crossbow.vmt"	"file"
	"materials/hud/leaderboard_class_medic_crossbow.vtf"	"file"
	"materials/hud/leaderboard_class_medic_jug_amputator2.vmt"	"file"
	"materials/hud/leaderboard_class_medic_jug_amputator2.vtf"	"file"
	"materials/hud/leaderboard_class_medic_kritz.vmt"	"file"
	"materials/hud/leaderboard_class_medic_kritz.vtf"	"file"
	"materials/hud/leaderboard_class_potion_trap_lite.vmt"	"file"
	"materials/hud/leaderboard_class_potion_trap_lite.vtf"	"file"
	"materials/hud/leaderboard_class_pyro_fireaxe_lite.vmt"	"file"
	"materials/hud/leaderboard_class_pyro_fireaxe_lite.vtf"	"file"
	"materials/hud/leaderboard_class_scout_blaster_nys.vmt"	"file"
	"materials/hud/leaderboard_class_scout_blaster_nys.vtf"	"file"
	"materials/hud/leaderboard_class_scout_sunstick.vmt"	"file"
	"materials/hud/leaderboard_class_sniper_carbine.vmt"	"file"
	"materials/hud/leaderboard_class_sniper_carbine.vtf"	"file"
	"materials/hud/leaderboard_class_sniper_jug_trivalshiv.vmt"	"file"
	"materials/hud/leaderboard_class_sniper_jug_trivalshiv.vtf"	"file"
	"materials/hud/leaderboard_class_spy_letranger_nys.vmt"	"file"
	"materials/hud/leaderboard_class_spy_letranger_nys.vtf"	"file"
	"models/empty.phy"	"file"
	"models/props_halloween/flask_tub.phy"	"file"
	"models/workshop/player/items/demo/tw_sentrybuster/tw_sentrybuster.phy"	"file"
	"models/workshop/weapons/c_models/c_nailgun/c_nailgun.phy" "file"
}
