Resources
{
	"materials/hud/leaderboard_class_heavy_natascha_nys.vtf"	"file"
	"materials/hud/leaderboard_class_heavy_natascha_nys_giant.vmt"	"file"
	"materials/hud/leaderboard_class_red2_lite.vmt"	"file"
	"materials/hud/leaderboard_class_red2_lite.vtf"	"file"
	"materials/hud/leaderboard_class_scout_sunstick.vmt"	"file"
	"materials/hud/leaderboard_class_sniper_smg_tind.vmt"	"file"
	"materials/hud/leaderboard_class_sniper_smg_tind.vtf"	"file"
	"materials/hud/leaderboard_class_soldier_barrage_charged.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_barrage_charged.vtf"	"file"
	"materials/hud/leaderboard_class_soldier_bison.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_bison.vtf"	"file"
	"materials/hud/leaderboard_class_soldier_burstfire_buff.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_burstfire_buff.vtf"	"file"
	"materials/hud/leaderboard_class_soldier_homing_nys.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_homing_nys.vtf"	"file"
	"materials/hud/leaderboard_class_soldier_mangler.vtf"	"file"
	"materials/hud/leaderboard_class_soldier_mangler_giant.vmt"	"file"
}
