Resources
{
	"materials/hud/leaderboard_class_blimp2_laser_lite.vmt"	"file"
	"materials/hud/leaderboard_class_heavy_brass_nys.vmt"	"file"
	"materials/hud/leaderboard_class_heavy_brass_nys.vtf"	"file"
	"materials/hud/leaderboard_class_heavy_family_business_lite.vmt"	"file"
	"materials/hud/leaderboard_class_pyro_dragon_fury_swordstone.vmt"	"file"
	"materials/hud/leaderboard_class_pyro_dragon_fury_swordstone.vtf"	"file"
	"materials/hud/leaderboard_class_scout_milk.vmt"	"file"
	"materials/hud/leaderboard_class_scout_milk.vtf"	"file"
	"materials/hud/leaderboard_class_scout_sunstick.vmt"	"file"
	"materials/hud/leaderboard_class_scout_wrap_lite.vmt"	"file"
	"materials/hud/leaderboard_class_spellbook_lite.vmt"	"file"
	"materials/hud/leaderboard_class_spellbook_lite_giant.vmt"	"file"
	"materials/hud/leaderboard_class_wheelofdoom_crits.vmt"	"file"
	"models/bots/boss_bot/boss_blimp.dx80.vtx"	"file"
	"models/bots/boss_bot/boss_blimp.dx90.vtx"	"file"
	"models/bots/boss_bot/boss_blimp.mdl"	"file"
	"models/bots/boss_bot/boss_blimp.phy"	"file"
	"models/bots/boss_bot/boss_blimp.vvd"	"file"
	"models/props_lakeside_event/buff_plane.phy"	"file"
	"models/props_spytech/raygun003.phy"	"file"
}
